[project]
name = "cocotest"
version = "0.1.0"
description = "Lightweight, opinionated test orchestration framework for cocotb."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Pierre-Louis Nordmann" }]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Software Development :: Testing",
]
requires-python = ">=3.11"
dependencies = ["cocotb~=2.0.1", "psutil>=7.2.2"]

[project.urls]
Homepage = "https://github.com/p-nordmann/cocotest"
Repository = "https://github.com/p-nordmann/cocotest"
Issues = "https://github.com/p-nordmann/cocotest/issues"

[project.scripts]
cocotest = "cocotest.cli:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pytest>=9.1.1"]

[tool.pytest.ini_options]
# We use the pytest option below to make sure that pytest does not try
# to interpret Cocotest's TestXxx classes as actual tests.
collect_imported_tests = false
